version: '3.0'

services:
  grafana:
    user: root
    container_name: 'bitmovin-analytics-datasource'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.1.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/bitmovin-analytics-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/bitmovin-analytics-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.bitmovin-analytics-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: bitmovin-analytics-datasource
      GF_PLUGINS_DELVE_ENABLED: 1
