{
 "title": "Bitmovin Analytics",
 "description": "Example Bitmovin Analytics Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Plays vs Error Plays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Total",
     "dimension": "IMPRESSION_ID",
     "filter": [
      { "name": "VIDEO_STARTUPTIME", "operator": "GT", "value": "0" }
     ],
     "metric": "count"
    },
    {
     "alias": "Error",
     "dimension": "IMPRESSION_ID",
     "filter": [
      { "name": "ERROR_CODE", "operator": "NE", "value": "" },
      { "name": "ERROR_CODE", "operator": "NE", "value": "10000" }
     ],
     "metric": "count"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimension": "ERROR_PERCENTAGE",
     "filter": [
      { "name": "ERROR_CODE", "operator": "NE", "value": "10000" }
     ],
     "metric": "avg"
    }
   ]
  },
  {
   "title": "Rebuffer Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "dimension": "REBUFFER_PERCENTAGE", "metric": "avg" }
   ]
  },
  {
   "title": "Total Hours Watched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimension": "PLAYED",
     "filter": [
      { "name": "PLAYED", "operator": "GT", "value": "0" }
     ],
     "metric": "sum"
    }
   ]
  },
  {
   "title": "Concurrent Viewers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "dimension": "MAX_CONCURRENTVIEWERS" }
   ]
  },
  {
   "title": "Plays per Browser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dimension": "IMPRESSION_ID",
     "filter": [
      { "name": "VIDEO_STARTUPTIME", "operator": "GT", "value": "0" }
     ],
     "groupBy": [ "BROWSER" ],
     "metric": "count"
    }
   ]
  },
  {
   "title": "Plays per Country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dimension": "IMPRESSION_ID",
     "filter": [
      { "name": "VIDEO_STARTUPTIME", "operator": "GT", "value": "0" }
     ],
     "groupBy": [ "COUNTRY" ],
     "metric": "count"
    }
   ]
  },
  {
   "title": "Plays per Player Technology",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "dimension": "IMPRESSION_ID",
     "filter": [
      { "name": "VIDEO_STARTUPTIME", "operator": "GT", "value": "0" }
     ],
     "groupBy": [ "PLAYER_TECH" ],
     "metric": "count",
     "orderBy": [
      { "name": "FUNCTION", "order": "DESC" }
     ]
    }
   ]
  },
  {
   "title": "Plays per Operating System",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "targets": [
    {
     "dimension": "IMPRESSION_ID",
     "filter": [
      { "name": "VIDEO_STARTUPTIME", "operator": "GT", "value": "0" }
     ],
     "groupBy": [ "OPERATINGSYSTEM" ],
     "limit": 10,
     "metric": "count",
     "orderBy": [
      { "name": "FUNCTION", "order": "DESC" }
     ]
    }
   ]
  },
  {
   "title": "Plays per Browser",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "targets": [
    {
     "dimension": "IMPRESSION_ID",
     "groupBy": [ "BROWSER" ],
     "limit": 10,
     "metric": "count",
     "orderBy": [
      { "name": "FUNCTION", "order": "DESC" }
     ]
    }
   ]
  },
  {
   "title": "Plays per Country",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "dimension": "IMPRESSION_ID",
     "groupBy": [ "COUNTRY" ],
     "limit": 10,
     "metric": "count",
     "orderBy": [
      { "name": "FUNCTION", "order": "DESC" }
     ]
    }
   ]
  }
 ]
}