name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    #TODO delete after merge to main
    defaults:
      run:
        working-directory: ./bitmovin-analytics-datasource
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          #TODO delete after merge to main
          cache-dependency-path: './bitmovin-analytics-datasource/yarn.lock'
      - name: Install dependencies
        run: yarn install --immutable --prefer-offline
      - name: Build plugin
        run: yarn run build
      - name: Compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/ui,@grafana/runtime
